// Datos ficticios de demostración — ningún dato aquí corresponde a personas reales.

const PATIENTS = [
  {
    id: "p1",
    nombre: "María Fernanda Torres Quispe",
    iniciales: "MT",
    edad: 34,
    dni: "45 218 903",
    telefono: "987 214 356",
    nacimiento: "12/03/1992",
    direccion: "Jr. Los Álamos 342, Huancayo",
    ultimaVisita: "2026-07-30",
    tag: "Tratamiento en curso",
    consultas: [
      { fecha: "2026-07-30", tipo: "Endodoncia", nota: "Endodoncia pieza 36, segunda sesión. Paciente refiere leve sensibilidad al frío. Se programa control en 15 días." },
      { fecha: "2026-06-18", tipo: "Endodoncia", nota: "Inicio de endodoncia pieza 36 por caries profunda. Se coloca medicación intraconducto." },
      { fecha: "2026-04-02", tipo: "Consulta general", nota: "Control de rutina. Diagnóstico de caries en pieza 36. Se indica endodoncia." },
    ],
    archivos: [
      { tipo: "Radiografía periapical", fecha: "2026-06-18", pieza: "Pieza 36" },
      { tipo: "Foto intraoral", fecha: "2026-04-02", pieza: "Cuadrante inferior izquierdo" },
    ],
    odontograma: {
      36: { condicion: "endodoncia", nota: "Endodoncia en curso, 2da sesión" },
      17: { condicion: "obturacion", nota: "Resina O, buen estado" },
    },
  },
  {
    id: "p2",
    nombre: "Jorge Luis Ramírez Huamán",
    iniciales: "JR",
    edad: 27,
    dni: "70 933 812",
    telefono: "912 445 780",
    nacimiento: "05/11/1998",
    direccion: "Av. Ferrocarril 1180, Huancayo",
    ultimaVisita: "2026-07-22",
    tag: "Control",
    consultas: [
      { fecha: "2026-07-22", tipo: "Extracción", nota: "Extracción simple pieza 18 (tercer molar semi-incluido). Se indica antiinflamatorio por 3 días y dieta blanda." },
      { fecha: "2026-07-08", tipo: "Consulta general", nota: "Evaluación de dolor en zona posterior derecha. Se solicita radiografía panorámica." },
    ],
    archivos: [
      { tipo: "Radiografía panorámica", fecha: "2026-07-08", pieza: "Vista completa" },
    ],
    odontograma: {
      18: { condicion: "extraccion", nota: "Extraído — tercer molar semi-incluido" },
      47: { condicion: "caries", nota: "Caries O, pendiente evaluar" },
    },
  },
  {
    id: "p3",
    nombre: "Ana Lucía Vargas Mendoza",
    iniciales: "AV",
    edad: 45,
    dni: "41 720 655",
    telefono: "998 601 223",
    nacimiento: "19/08/1980",
    direccion: "Jr. Cusco 512, El Tambo",
    ultimaVisita: "2026-07-10",
    tag: "Estable",
    consultas: [
      { fecha: "2026-07-10", tipo: "Limpieza dental", nota: "Profilaxis y destartraje. Buena higiene oral. Se recomienda control cada 6 meses." },
      { fecha: "2026-01-14", tipo: "Resina", nota: "Resina compuesta en pieza 21 por caries interproximal. Sin complicaciones." },
    ],
    archivos: [
      { tipo: "Foto intraoral", fecha: "2026-01-14", pieza: "Pieza 21" },
    ],
    odontograma: {
      21: { condicion: "obturacion", nota: "Resina interproximal" },
      36: { condicion: "preventivo", nota: "Sellante aplicado" },
    },
  },
  {
    id: "p4",
    nombre: "Carlos Alberto Paredes Rojas",
    iniciales: "CP",
    edad: 52,
    dni: "22 480 917",
    telefono: "945 332 190",
    nacimiento: "27/02/1974",
    direccion: "Ca. Real 890, Huancayo",
    ultimaVisita: "2026-07-05",
    tag: "Requiere seguimiento",
    consultas: [
      { fecha: "2026-07-05", tipo: "Consulta general", nota: "Diagnóstico de enfermedad periodontal moderada. Se inicia tratamiento periodontal por fases." },
      { fecha: "2026-05-20", tipo: "Radiografía", nota: "Radiografía panorámica de control anual. Se observa pérdida ósea leve en molares inferiores." },
    ],
    archivos: [
      { tipo: "Radiografía panorámica", fecha: "2026-05-20", pieza: "Vista completa" },
      { tipo: "Foto intraoral", fecha: "2026-07-05", pieza: "Encía inferior" },
    ],
    odontograma: {
      46: { condicion: "preventivo", nota: "Control periodontal, bolsa 4mm" },
      37: { condicion: "preventivo", nota: "Control periodontal, bolsa 5mm" },
    },
  },
  {
    id: "p5",
    nombre: "Lucía Beatriz Salazar Chávez",
    iniciales: "LS",
    edad: 19,
    dni: "76 154 208",
    telefono: "961 780 445",
    nacimiento: "30/09/2006",
    direccion: "Av. Mariscal Castilla 245, El Tambo",
    ultimaVisita: "2026-07-28",
    tag: "Ortodoncia",
    consultas: [
      { fecha: "2026-07-28", tipo: "Control de ortodoncia", nota: "Ajuste mensual de brackets. Buena evolución de alineación. Próximo control en 4 semanas." },
      { fecha: "2026-06-30", tipo: "Control de ortodoncia", nota: "Cambio de arco. Se refuerza indicación de higiene con cepillo interdental." },
    ],
    archivos: [
      { tipo: "Foto intraoral", fecha: "2026-06-30", pieza: "Vista frontal" },
    ],
  },
  {
    id: "p6",
    nombre: "Miguel Ángel Fernández Cruz",
    iniciales: "MF",
    edad: 61,
    dni: "18 903 442",
    telefono: "934 217 668",
    nacimiento: "11/06/1965",
    direccion: "Jr. Amazonas 733, Chilca",
    ultimaVisita: "2026-06-12",
    tag: "Prótesis",
    consultas: [
      { fecha: "2026-06-12", tipo: "Prótesis dental", nota: "Toma de impresión para prótesis parcial removible superior. Se cita para prueba de metal en 2 semanas." },
    ],
    archivos: [
      { tipo: "Radiografía panorámica", fecha: "2026-06-12", pieza: "Vista completa" },
    ],
    odontograma: {
      36: { condicion: "extraccion", nota: "Ausente — pilar de prótesis parcial" },
      46: { condicion: "extraccion", nota: "Ausente — pilar de prótesis parcial" },
      26: { condicion: "implante", nota: "Implante 2023, oseointegrado" },
    },
  },
  {
    id: "p7",
    nombre: "Rosa Elena Gutiérrez Flores",
    iniciales: "RG",
    edad: 38,
    dni: "40 118 265",
    telefono: "923 556 810",
    nacimiento: "04/12/1987",
    direccion: "Ca. Puno 401, Huancayo",
    ultimaVisita: "2026-07-30",
    tag: "Nueva paciente",
    consultas: [
      { fecha: "2026-07-30", tipo: "Consulta general", nota: "Primera consulta. Evaluación general, se realiza odontograma completo. Sin urgencias." },
    ],
    archivos: [],
    odontograma: {
      14: { condicion: "caries", nota: "Caries O incipiente, observar" },
      26: { condicion: "caries", nota: "Caries O, requiere resina" },
    },
  },
  {
    id: "p8",
    nombre: "Diego Alonso Castillo Vega",
    iniciales: "DC",
    edad: 8,
    dni: "DNI menor 84 220 011",
    telefono: "987 004 552 (madre)",
    nacimiento: "14/02/2018",
    direccion: "Jr. Junín 220, Huancayo",
    ultimaVisita: "2026-07-18",
    tag: "Odontopediatría",
    consultas: [
      { fecha: "2026-07-18", tipo: "Aplicación de flúor", nota: "Aplicación tópica de flúor. Buena colaboración del paciente. Se refuerza técnica de cepillado con la madre." },
      { fecha: "2026-05-02", tipo: "Consulta general", nota: "Primera visita odontopediátrica. Sin caries activas. Se indica control cada 6 meses." },
    ],
    archivos: [
      { tipo: "Foto intraoral", fecha: "2026-05-02", pieza: "Dentición temporal" },
    ],
  },
];
